# NN Test

In [2]:
from si.neural_networks.layers import Dense, SigmoidActivation, SoftMaxActivation, ReLUActivation, LinearActivation
from si.neural_networks.nn import NN
from si.data.dataset import Dataset
import numpy as np

In [3]:
x = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([1,
              0,
              0,
              1])

dataset = Dataset(x=x, y=y, features_names=['x1', 'x2'], label_name='x1 XNOR x2')
dataset.print_dataframe()

x1  x2
1   0   0
0   0   1
0   1   0
1   1   1

In [4]:
# weights and bias for the 1st layer

# first row is the first node of the second layer
# rows are the input nodes
l1_weight_matrix = np.array([[20, -20],
                             [20, -20]])

l1_bias = np.array([[-30, 10]])

layer1 = Dense(input_size=2, output_size=2)
layer1.weights = l1_weight_matrix
layer1.bias = l1_bias

In [5]:
# weights and bias for the 2nd layer

l2_weight_matrix = np.array([[20],
                             [20]])

l2_bias = np.array([[-10]])

layer2 = Dense(input_size=2, output_size=1)
layer2.weights = l2_weight_matrix
layer2.bias = l2_bias

In [45]:
layer1_sigmoid = SigmoidActivation()
layer2_sigmoid = SigmoidActivation()

# between layers, we have the layer activation
nn_model = NN(
    layers=[layer1, layer1_sigmoid, layer2, layer2_sigmoid]
)

In [46]:
nn_model.fit(dataset=dataset)

In [48]:
nn_model.predict(dataset=dataset)

array([[9.99954561e-01],
       [4.54803785e-05],
       [4.54803785e-05],
       [9.99954561e-01]])

## Ex.10 Evaluation

### Ex.10.3
Binary classification problem

In [7]:
# Create an adequate training dataset
x_3 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_3 = np.random.randint(0, 2, size=(100, 1))  # labels for the 100 samples of random binary integers

dataset_3 = Dataset(x_3, y_3)

In [8]:
layer3_1 = Dense(input_size=32, output_size=32)
layer3_2 = Dense(input_size=32, output_size=16)
layer3_3 = Dense(input_size=16, output_size=1)  #if score is <0.5 the output is 0, and if score is >0.5 the output is 1

layer3_1activation = SigmoidActivation()
layer3_2activation = SigmoidActivation()
layer3_3activation= SigmoidActivation()

# between layers, we have the layer activation
nn_model3 = NN(
    layers=[layer3_1, layer3_1activation, layer3_2, layer3_2activation, layer3_3, layer3_3activation]
)

In [9]:
nn_model3.fit(dataset=dataset_3)

In [10]:
nn_model3.predict(dataset=dataset_3)

array([[0.49531054],
       [0.49531202],
       [0.49531226],
       [0.49531231],
       [0.49530959],
       [0.49531031],
       [0.49530841],
       [0.49531074],
       [0.49531313],
       [0.49531266],
       [0.49531117],
       [0.49531007],
       [0.49530977],
       [0.49531537],
       [0.49531297],
       [0.49531032],
       [0.49530931],
       [0.49531098],
       [0.49530775],
       [0.49531011],
       [0.49531225],
       [0.49531541],
       [0.49531345],
       [0.495309  ],
       [0.49531431],
       [0.49531149],
       [0.49531263],
       [0.49531111],
       [0.49531024],
       [0.49530993],
       [0.49531263],
       [0.49531377],
       [0.49531327],
       [0.49531067],
       [0.49531117],
       [0.49530926],
       [0.49531016],
       [0.49531077],
       [0.49531369],
       [0.49531144],
       [0.49531121],
       [0.49530972],
       [0.4953091 ],
       [0.49531303],
       [0.49531048],
       [0.4953079 ],
       [0.49531402],
       [0.495

### Ex.10.4
Multiclass classification problem (3 classes)

In [11]:
# Create an adequate training dataset
x_4 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_4 = np.random.randint(0, 3, size=(100, 1))  # labels for the 100 samples with 3 different classes

dataset_4 = Dataset(x_4, y_4)

In [12]:
layer4_1 = Dense(input_size=32, output_size=32)
layer4_2 = Dense(input_size=32, output_size=16)
layer4_3 = Dense(input_size=16, output_size=3)  # will assign each output to the corresponding class according to the score

layer4_1activation = SigmoidActivation()
layer4_2activation= SigmoidActivation()
layer4_3activation = SoftMaxActivation()  # will assign a probability to each class that summed together will add up to 1

# between layers, we have the layer activation
nn_model4 = NN(
    layers=[layer4_1, layer4_1activation, layer4_2, layer4_2activation, layer4_3, layer4_3activation]
)

In [13]:
nn_model4.fit(dataset=dataset_4)

In [14]:
nn_model4.predict(dataset=dataset_4)

array([[0.33869774, 0.33102582, 0.33027644],
       [0.33870107, 0.33102503, 0.33027389],
       [0.33870404, 0.33102199, 0.33027397],
       [0.33870075, 0.33102475, 0.33027449],
       [0.33870338, 0.33102391, 0.33027271],
       [0.33870375, 0.33102629, 0.33026996],
       [0.33870223, 0.33102258, 0.33027519],
       [0.33869857, 0.33102539, 0.33027605],
       [0.33870193, 0.33102563, 0.33027244],
       [0.33870059, 0.33102557, 0.33027384],
       [0.33869906, 0.33102388, 0.33027706],
       [0.33870234, 0.33102509, 0.33027257],
       [0.33870123, 0.33102504, 0.33027372],
       [0.33869999, 0.3310242 , 0.33027581],
       [0.33869913, 0.33102529, 0.33027558],
       [0.33869946, 0.3310246 , 0.33027594],
       [0.33869897, 0.33102422, 0.33027681],
       [0.33870048, 0.33102497, 0.33027455],
       [0.33869898, 0.3310249 , 0.33027611],
       [0.33869956, 0.33102591, 0.33027453],
       [0.33870149, 0.33102652, 0.33027198],
       [0.33870234, 0.33102335, 0.33027431],
       [0.

### Ex.10.5
Regression problem

In [15]:
# Create an adequate training dataset
x_5 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_5 = np.random.randn(100, 1)  # labels for the 100 samples of random floats

dataset_5 = Dataset(x_5, y_5)

In [16]:
layer5_1 = Dense(input_size=32, output_size=32)
layer5_2 = Dense(input_size=32, output_size=16)
layer5_3 = Dense(input_size=16, output_size=1)  # returns a single continuous target for each sample

layer5_1activation = ReLUActivation()
layer5_2activation = ReLUActivation()
layer5_3activation = LinearActivation()  # returns a real values for our output

# between layers, we have the layer activation
nn_model5 = NN(
    layers=[layer5_1, layer5_1activation, layer5_2, layer5_2activation, layer5_3, layer5_3activation]
)

In [17]:
nn_model5.fit(dataset=dataset_5)

In [18]:
nn_model5.predict(dataset=dataset_5)

array([[-6.60358704e-05],
       [-1.12359754e-05],
       [-1.06814322e-05],
       [-2.76392044e-05],
       [ 2.13469987e-05],
       [-3.28900541e-05],
       [ 1.76485669e-05],
       [ 9.64168790e-06],
       [-3.67726719e-05],
       [-1.77240298e-05],
       [-1.75230350e-05],
       [ 1.28876323e-04],
       [-2.17718571e-05],
       [-5.96350542e-05],
       [ 2.65359736e-05],
       [ 2.46386781e-05],
       [ 2.19052468e-05],
       [ 5.06382657e-06],
       [-7.27715136e-06],
       [ 1.10217510e-05],
       [ 1.40806531e-05],
       [-6.39781703e-05],
       [ 2.39786576e-07],
       [ 4.13656276e-05],
       [-2.29751322e-05],
       [-3.36637186e-05],
       [-2.43219275e-05],
       [-2.14289027e-05],
       [ 8.35662083e-05],
       [-4.42453840e-05],
       [-3.89488564e-05],
       [ 3.58399024e-06],
       [ 2.62989095e-05],
       [-2.17567413e-05],
       [-2.98511016e-05],
       [ 6.73300754e-05],
       [-2.11959912e-05],
       [ 3.79895509e-07],
       [ 6.5